### ISSUE TITLE
What do we use for the project number?

### ISSUE THREAD

**Issue by 365SplendidSuns** [tkohout/fastlane-firebase-plugin#5]
I assumed that setting the project_number parameter to "1" (The same as I enter when selecting the project manually) would allow the project to be chosen automatically but this doesn't work. Is there another project number I need to use? I could only see a project id in Firebase and using this doesn't work either. Thanks.

**Comment by 365SplendidSuns** [comment]
OK. I've figured it out but thought I'd leave the answer here as it's not obvious rather than delete my question. The project_number is a number assigned to the project within Firebase but for whatever reason (Maybe they've made changes recently to only display the project ID??) it isn' viewable in the Firebase site. It isn't in the iOS GoogleService-Info.plist file either but it is in the Android google-services.json file. So look for it there.

**Comment by tkohout** [comment]
Hello,
you can use `firebase_list` to show list of your projects with their project number.

It might be good idea to add it to other actions also.

**Comment by 365SplendidSuns** [comment]
Hi,

So you can! I should have spotted that earlier. Thanks for the plugin btw - great job and a massive timesaver.
